name: CI Energy Estimations

on:
  workflow_dispatch:
    inputs:
      space:
        description: 'Select the Deployment Stage'
        required: true
        type: choice
        options:
          - 'DEV'
          - 'INT'
          - 'PROD'

      bg-deploy:
        description: 'Run as Blue/Green Deployment?'
        required: true
        default: false
        type: boolean

      git-ref:
        description: 'Set the Git Tag, Branch (e.g. main) or Commit SHA'
        required: true
        default: 'main'
        type: string

jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    name: JavaScript tests
    steps:
      - name: Eco-CI Init
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: start-measurement

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package.json'
      - run: npm install
      - run: npm test

      - name: Eco-CI Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: get-measurement
          label: 'npm tests'

      - name: Eco-CI Results
        uses: green-coding-berlin/eco-ci-energy-estimation@main
        with:
          task: display-results
